showTodos:
  path: /{all}/{id}
  controller: App\Controller\TodosController::showTodos
  defaults:
    all: 0
    id: 0

updateTodo:
  path: /update/{id}/completed/{completed}
  controller: App\Controller\TodosController::updateTodo
